In [1]:
import os
import numpy as np
import nibabel as nib

In [5]:
path = "/workspace/dwseon/dat/b4_raw/"
pList = os.listdir(path)
pList = [os.path.join(path, p) for p in pList]
pList = [os.path.join(p, "b4_reg_seg.nii.gz") for p in pList]

In [44]:
a = np.array([[1,2,3], [0, 6, 1]]).astype(int)
print(a[1])
print(a[1][a[1]>2])
print(a*0)

[0 6 1]
[6]
[[0 0 0]
 [0 0 0]]


In [58]:
# Labeling mistakes, patient:slices
edit_target = {"088":[27], "076":[31, 20], "060":[23],
               "038":[12], "037":[14,28], "024":[32]}

def fixxxx(dic):
    for patient, slices in dic.items():
        # print(patient, slices)
        p = os.path.join(path, patient)
        p = os.path.join(p, "b4_reg_seg.nii.gz")
        img = nib.load(p)
        affine = img.affine # for consistency when saving
        img = img.get_fdata()
        # print(img[:, :, 0].shape)
        for slice in slices:
            # Don't forget to slice-1
            # print(f"patient {patient}, slice {slice}\n\033[31mb4\033[0m: {np.unique(img[:, :, slice-1])}")
            img[:, :, slice-1] = img[:, :, slice-1] * 0
            # print(f"\033[32mftr\033[0m: {np.unique(img[:, :, slice-1])}")
        mod = nib.Nifti1Image(img, affine)
        nib.save(mod, os.path.join(path, f"{patient}/b4_reg_seg_fix.nii.gz"))
        print(f"\033[31mDone\033[0m for patient \033[32m{patient}\033[0m!", end="\r")

In [59]:
fixxxx(edit_target)

In [60]:
def switch_names(dic):
    # Done with fixing AND checking up on them?
    # Rename them to their rightful original name
    for patient, _ in dic.items():
        p = os.path.join(path, patient)
        fro = os.path.join(p, "b4_reg_seg_fix.nii.gz")
        target = os.path.join(p, "b4_reg_seg.nii.gz")
        # remove dirty ones first
        os.remove(target)
        os.rename(fro, target)

In [61]:
switch_names(edit_target)